etcd:
  userName:
  password:
  secret: "4MP0%n8@3ZjK1yAo9mP"

mysql:
  dbMysqlUserName: root
  dbMysqlPassword: "openIM123"

mongo:
  dbUserName:          root
  dbPassword: "kP1Tf@J7m2O7TJtR"

redis:
  dbUserName: root
  dbPassWord: "oNZKCK137!Fne7F!v7gm"

kafka:
  SASLUserName:
  SASLPassword:

credential:
  minio:
    endpoint: http://13.215.128.181:9000
    accessKeyID: root
<<<<<<< HEAD
    secretAccessKey: "H5p@gyQb*L@#5Y18GsVA"

secret: "4MP0%n8@3ZjK1yAo9mP"
=======
    secretAccessKey: 4MP0%n8@3ZjK1yAo9

secret: 4MP0%n8@3ZjK1yAo9
>>>>>>> ba44bcc6649c6582c041e3f37a4195621227f5c3

tokenpolicy:
  accessSecret: "open_im_server" #token生成相关 建议修改
  accessExpire: 90 #token过期时间（天） 默认即可

messageverify:
  friendVerify: true #发送消息是否验证好友关系 false表示不验证好友关系

push:
  getui:
    pushUrl: "https://restapi.getui.com/v2/$appId"
    masterSecret: "tOUxUYulLS6PXmnxIXPR16"  #需添加
    appKey: "tt4SSYU5gx8cT46vuddVW"  #需添加
    enable: true  #:true启动个推推送

