etcd:
  userName:
  password:
  secret: 4MP0%n8@3ZjK1yAo9

mysql:
  dbMysqlUserName: root
  dbMysqlPassword: 4MP0%n8@3ZjK1yAo9

mongo:
  dbUserName:  root
  dbPassword: 4MP0%n8@3ZjK1yAo9

redis:
  dbUserName: root
  dbPassWord: 4MP0%n8@3ZjK1yAo9

kafka:
  SASLUserName:
  SASLPassword:

credential:
  minio:
    endpoint: http://13.215.128.181:9000
    accessKeyID: root
    secretAccessKey: 4MP0%n8@3ZjK1yAo9

secret: 4MP0%n8@3ZjK1yAo9

tokenpolicy:
  accessSecret: "open_im_server" #token生成相关 建议修改
  accessExpire: 90 #token过期时间（天） 默认即可

messageverify:
  friendVerify: true #发送消息是否验证好友关系 false表示不验证好友关系

push:
  getui:
    pushUrl: "https://restapi.getui.com/v2/$appId"
    masterSecret: "tOUxUYulLS6PXmnxIXPR16"  #需添加
    appKey: "tt4SSYU5gx8cT46vuddVW"  #需添加
    enable: true  #:true启动个推推送

